### ISSUE TITLE
Collecting data from a container

### ISSUE THREAD

**Issue by jasnell** [nearform/node-clinic#10]
One feature that would be exceedingly helpful for clinic would be the ability to run it against a node process running within a container. Not yet entirely sure how that would work seamlessly, but wanted to at least open a tracking issue. 

For example:
```
$ clinic doctor -- docker run myApp
```

**Comment by IvanJov** [comment]
This would be really great! I was testing the app yesterday from a docker container and one solution was to update the start script in package.json to include clinic. It will be great to have the easier way 😄

**Comment by sumitsk20** [comment]
@IvanJov can you please share the code how can i run clinic inside the docker container. I have modified my start script with docker but it is not creating any traceevent file, it only creates a .clinic folder

**Comment by dam1r89** [comment]
Assuming that you've changed start script to run clinic, you have to send SIGINT to the clinic to make it stop gracefully and to generate reports.

I'm using docker-compose so this is how I did it: 

Connect to running instance `docker-compose exec node bash` then type `ps x` and find process PID of the clinic. Something like `node /app/node_modules/.bin/clinic flame -- node dist/server.js`.

Then send the stop signal with `kill -SIGINT <PID>` and do it twice. Then it will stop in few seconds and generate reports.

Hope this helps somebody.

**Comment by goto-bus-stop** [comment]
The SIGINT thing is correct—you can also run clinic using the `timeout` command-line tool to automatically stop after a certain time:

```bash
# start.sh
timeout --signal=SIGINT 20s clinic doctor -- node server.js
```
```bash
# Dockerfile
CMD ["/bin/bash", "./start.sh"]
```

**Comment by shahyar** [comment]
Bringing this old issue back up. Host macOS and container Debian with Node v12.18 inside. Despite issuing SIGINT with the proposed solutions, the process ends up like this:
```
[=== ] Received Ctrl+C, closing process...Error: No files matching the pattern found
    at notFound (/usr/local/lib/node_modules/clinic/node_modules/@nearform/node-trace-log-join/index.js:66:15)
    at combine (/usr/local/lib/node_modules/clinic/node_modules/@nearform/node-trace-log-join/index.js:25:34)
    at /usr/local/lib/node_modules/clinic/node_modules/@nearform/node-trace-log-join/index.js:21:5
    at FSReqCallback.oncomplete (fs.js:156:23)
```

It creates the `stacktrace` and `systeminfo` files, but no `traceevent`. My initial guess it's a compatibility issue with Node v12, but going to v10 isn't an option in my case. Likely related to #257 and #268.

**Comment by aakarim** [comment]
With docker-compose you can do this:
`docker-compose kill -s SIGINT`

**Comment by Stono** [comment]
It'd be really great to not have to stop the process, is there something about the implementation that means it requires the process to be terminated to generate the samples?  Basically in a container i'd love to start clinic, then send a signal that dumps the data up to that point, so i can grab it, without restarting the process.
