### ISSUE TITLE
Error on Node.js 9.4.0: 'timestamp' of undefined

### ISSUE THREAD

**Issue by DanielRuf** [nearform/node-clinic#14]
```
clinic doctor -- node index.js
Warning: Trace event is an experimental feature and could change at any time.
16
analysing data
/opt/nodes/9.4.0/lib/node_modules/clinic/node_modules/@nearform/clinic-doctor/analysis/index.js:42
      processStat[intervalIndex[0]].timestamp,
                                    ^

TypeError: Cannot read property 'timestamp' of undefined
    at /opt/nodes/9.4.0/lib/node_modules/clinic/node_modules/@nearform/clinic-doctor/analysis/index.js:42:37
    at /opt/nodes/9.4.0/lib/node_modules/clinic/node_modules/async/dist/async.js:3874:9
    at /opt/nodes/9.4.0/lib/node_modules/clinic/node_modules/async/dist/async.js:473:16
    at iterateeCallback (/opt/nodes/9.4.0/lib/node_modules/clinic/node_modules/async/dist/async.js:980:24)
    at /opt/nodes/9.4.0/lib/node_modules/clinic/node_modules/async/dist/async.js:958:16
    at /opt/nodes/9.4.0/lib/node_modules/clinic/node_modules/async/dist/async.js:3871:13
    at Endpoint.finish (/opt/nodes/9.4.0/lib/node_modules/clinic/node_modules/endpoint/endpoint.js:36:5)
    at Object.onceWrapper (events.js:255:19)
    at Endpoint.emit (events.js:165:20)
    at finishMaybe (_stream_writable.js:633:14)
```

**Comment by DanielRuf** [comment]
Same with Node.js 9.9.0

**Comment by mafintosh** [comment]
Anyway you can share the program you are trying to profile?

**Comment by DanielRuf** [comment]
It is just a simple oneliner (a function with a simple `console.log`).

Or does it just work with a script that does not directly terminate?

**Comment by AndreasMadsen** [comment]
@mafintosh I think this bug appears if the program exists so fast that it doesn't have time to collect any data.

**Comment by BridgeAR** [comment]
@mafintosh 

```js
'use strict';

console.log('Hello world!');
```
