### ISSUE TITLE
Exception on doctor analysing step

### ISSUE THREAD

**Issue by Skywalker13** [nearform/node-clinic#159]
## Expected Behavior
No JSON parsing exception

## Current Behavior
When I shutdown the app, the analysing is just failing... I start my app (it spawns multiples processes): `clinic doctor -- npm start`
```
[  ==] Analysing dataundefined:1
[{"pid":28671,"tid":28671,"ts":867159788650,"tts":4991138,"ph":"E","cat":"v8","name":"V8.Execute","dur":0,"tdur":0,"args":{"runtime-call-stats":{}}},{"pid":28671,"tid":28671,"ts":866991947586,"tts":11701,"ph":"M","cat":"__metadata","name":"process_name","dur":0,"tdur":0,"args":{"name":"node"}},{"pid":28671,"tid":28671,"ts":866991947589,"tts":11704,"ph":"M","cat":"__metadata","name":"version","dur":0,"tdur":0,"args":{"node":"10.15.2"}},{"pid":28671,"tid":28671,"ts":866991947590,"tts":11706,"ph":"M","cat":"__metadata","name":"thread_name","dur":0,"tdur":0,"args":{"name":"JavaScriptMainThread"}},{"pid":28671,"tid":28671,"ts":866991947611,"tts":11726,"ph":"M","cat":"__metadata","name":"node","dur":0,"tdur":0,"args":{"process":{"versions":{"http_parser":"2.8.0","node":"10.15.2","v8":"6.8.275.32-node.12","uv":"1.24.1","zlib":"1.2.11","ares":"1.14.0","modules":"64","nghttp2":"1.37.0","napi":"3","openssl":"1.1.1b"},"arch":"x64","platform":"linux","release":{"name":"node","lts":"Dubnium"}}}},{"pid":28671

SyntaxError: Unexpected token p in JSON at position 3698
    at JSON.parse (<anonymous>)
    at Parser._transform (/home/schroeterm/.npm-packages/lib/node_modules/clinic/node_modules/@nearform/trace-events-parser/index.js:41:34)
    at Parser.Transform._read (_stream_transform.js:190:10)
    at Parser.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Parser.Writable.write (_stream_writable.js:294:11)
    at TraceEventDecoder._transform (/home/schroeterm/.npm-packages/lib/node_modules/clinic/node_modules/@nearform/doctor/format/trace-event-decoder.js:114:19)
    at TraceEventDecoder.Transform._read (_stream_transform.js:190:10)
    at TraceEventDecoder.Transform._write (_stream_transform.js:178:12)
```

## Steps to Reproduce (for bugs)
I can't provide this app, sorry... But maybe I can provide more logs, but where and how ?

## Sample upload
N/A

## Environment
```
$ clinic -v
v4.0.3
$ clinic doctor -v
v4.0.4

$ node -v
v10.15.2
$ npm -v
6.9.0

$ uname -a
Linux alienium 4.19.0-4-amd64 #1 SMP Debian 4.19.28-2 (2019-03-15) x86_64 GNU/Linux
```

**Comment by JoaoPintoM** [comment]
Same issue here

**Comment by goto-bus-stop** [comment]
Multiple processes are not really supported at the moment. The instrumentation code will output JSON to stdout from every process, and it'll interleave and produce an invalid stream. It might be possible to support in the future but I'm not yet sure what it would take.

**Comment by robmcguinness** [comment]
@goto-bus-stop that was exactly my issue, thanks! removing `child_process` from main process solved the issue.
