### ISSUE TITLE
Error: Encountered an unparseable frame 

### ISSUE THREAD

**Issue by joma74** [nearform/node-clinic#171]
## Expected Behavior
report is generated

## Current Behavior
```
...
[serventest-prod] Analysing data
[serventest-prod] buffer/home/joma/.config/yarn/global/node_modules/clinic/bin.js:539
[serventest-prod]         if (err) throw err
[serventest-prod]                  ^
[serventest-prod] 
[serventest-prod] Error: Encountered an unparseable frame "internal/per_context/domexception.js"
[serventest-prod]     at new FrameNode (/home/joma/.config/yarn/global/node_modules/@nearform/flame/analysis/frame-node.js:71:15)
[serventest-prod]     at FrameNode.children.data.children.data.children.map (/home/joma/.config/yarn/global/node_modules/@nearform/flame/analysis/frame-node.js:18:38)
[serventest-prod]     at Array.map (<anonymous>)
[serventest-prod]     at new FrameNode (/home/joma/.config/yarn/global/node_modules/@nearform/flame/analysis/frame-node.js:18:23)
[serventest-prod]     at FrameNode.children.data.children.data.children.map (/home/joma/.config/yarn/global/node_modules/@nearform/flame/analysis/frame-node.js:18:38)
[serventest-prod]     at Array.map (<anonymous>)
[serventest-prod]     at new FrameNode (/home/joma/.config/yarn/global/node_modules/@nearform/flame/analysis/frame-node.js:18:23)
[serventest-prod]     at FrameNode.children.data.children.data.children.map (/home/joma/.config/yarn/global/node_modules/@nearform/flame/analysis/frame-node.js:18:38)
[serventest-prod]     at Array.map (<anonymous>)
[serventest-prod]     at new FrameNode (/home/joma/.config/yarn/global/node_modules/@nearform/flame/analysis/frame-node.js:18:23
...
```

## Steps to Reproduce (for bugs)
? v8 log was deleted
? can provide .clinic folder with one subfolder with 3 files

## Sample upload
fails before clinic upload message

## Environment
* Clinic.js version: v4.1.0
* Node.js version: v11.14.0
* Operating system and version:
Ubuntu 16.04.6 LTS

**Comment by DylanC** [comment]
@joma74 - Do you have a project you can attach to reproduce this issue?
