### ISSUE TITLE
Getting `'clockOffset' of undefined` when following the Getting Started guide

### ISSUE THREAD

**Issue by cowchimp** [nearform/node-clinic#199]
## Expected Behavior
Running the example from the "Getting Started" section should work successfully.

## Current Behavior
Getting `'clockOffset' of undefined` error when following the "Getting Started" example

<details>
  <summary>Cannot read property 'clockOffset' of undefined</summary>

```
➜  clinic doctor --autocannon [ / ] -- node ./slow-io
Running 10s test @ http://localhost:3000/
10 connections

┌─────────┬────────┬─────────┬─────────┬─────────┬────────────┬───────────┬────────────┐
│ Stat    │ 2.5%   │ 50%     │ 97.5%   │ 99%     │ Avg        │ Stdev     │ Max        │
├─────────┼────────┼─────────┼─────────┼─────────┼────────────┼───────────┼────────────┤
│ Latency │ 711 ms │ 1304 ms │ 1861 ms │ 1887 ms │ 1315.23 ms │ 341.29 ms │ 1887.37 ms │
└─────────┴────────┴─────────┴─────────┴─────────┴────────────┴───────────┴────────────┘
┌───────────┬───────┬───────┬────────┬─────────┬─────────┬───────┬───────┐
│ Stat      │ 1%    │ 2.5%  │ 50%    │ 97.5%   │ Avg     │ Stdev │ Min   │
├───────────┼───────┼───────┼────────┼─────────┼─────────┼───────┼───────┤
│ Req/Sec   │ 2     │ 2     │ 8      │ 9       │ 7       │ 2.05  │ 2     │
├───────────┼───────┼───────┼────────┼─────────┼─────────┼───────┼───────┤
│ Bytes/Sec │ 300 B │ 300 B │ 1.2 kB │ 1.35 kB │ 1.05 kB │ 307 B │ 300 B │
└───────────┴───────┴───────┴────────┴─────────┴─────────┴───────┴───────┘

Req/Bytes counts sampled once per second.

70 requests in 10.06s, 10.5 kB read
[    ] Analysing data/Users/cowchimp/temp/node-clinic-doctor-examples-master/node_modules/@nearform/doctor/format/trace-event-decoder.js:49
          self.clockOffset = systemInfo.clockOffset
                                        ^

TypeError: Cannot read property 'clockOffset' of undefined
    at /Users/cowchimp/temp/node-clinic-doctor-examples-master/node_modules/@nearform/doctor/format/trace-event-decoder.js:49:41
    at Endpoint.finish (/Users/cowchimp/temp/node-clinic-doctor-examples-master/node_modules/endpoint/endpoint.js:36:5)
    at Object.onceWrapper (events.js:281:20)
    at Endpoint.emit (events.js:198:15)
    at finishMaybe (_stream_writable.js:646:14)
    at endWritable (_stream_writable.js:663:3)
    at Endpoint.Writable.end (_stream_writable.js:594:5)
    at onend (/Users/cowchimp/temp/node-clinic-doctor-examples-master/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:627:10)
    at processTicksAndRejections (internal/process/task_queues.js:79:9)
```
</details>

## Steps to Reproduce (for bugs)

1. Test against `node-clinic-doctor-examples` as detailed here https://clinicjs.org/documentation
```
git clone git@github.com:nearform/node-clinic-doctor-examples.git
cd node-clinic-doctor-examples
npm install
clinic doctor --autocannon [ / ] -- node ./slow-io
```

## Environment
* Clinic.js version:
Clinic 5.0.0 and doctor 4.1.0
* Node.js version:
Node 11.14.0 and npm 6.9.0
* Browser name and version:
Chrome 78.0.3904.97
* Operating system and version:
OS X 10.13.6

**Comment by DylanC** [comment]
@cowchimp - I tried your above example and it worked for me. Bear in mind I have slightly different Env versions:

Clinic.js version:
Clinic 5.0.0 and doctor 4.1.0
Node.js version:
Node 12.14.1 and npm 6.9.7
Browser name and version:
Safari 13.0.4
Operating system and version:
OS X 10.14.6

**Comment by mrdowns** [comment]
The same thing is happening to me, both on the sample app and in my own codebase. Ran the sample app after this stopped me from using clinic in my own app.

```
➜  node-clinic-doctor-examples git:(master) clinic doctor --autocannon [ / ] -- node ./slow-io
? May Clinic.js report anonymous usage statistics to improve the tool over time? No
Running 10s test @ http://localhost:3000/
10 connections

┌─────────┬────────┬─────────┬─────────┬─────────┬────────────┬───────────┬────────────┐
│ Stat    │ 2.5%   │ 50%     │ 97.5%   │ 99%     │ Avg        │ Stdev     │ Max        │
├─────────┼────────┼─────────┼─────────┼─────────┼────────────┼───────────┼────────────┤
│ Latency │ 675 ms │ 1211 ms │ 1883 ms │ 1950 ms │ 1242.78 ms │ 301.25 ms │ 1950.16 ms │
└─────────┴────────┴─────────┴─────────┴─────────┴────────────┴───────────┴────────────┘
┌───────────┬───────┬───────┬────────┬────────┬─────────┬───────┬───────┐
│ Stat      │ 1%    │ 2.5%  │ 50%    │ 97.5%  │ Avg     │ Stdev │ Min   │
├───────────┼───────┼───────┼────────┼────────┼─────────┼───────┼───────┤
│ Req/Sec   │ 2     │ 2     │ 8      │ 10     │ 7.5     │ 2.34  │ 2     │
├───────────┼───────┼───────┼────────┼────────┼─────────┼───────┼───────┤
│ Bytes/Sec │ 300 B │ 300 B │ 1.2 kB │ 1.5 kB │ 1.13 kB │ 350 B │ 300 B │
└───────────┴───────┴───────┴────────┴────────┴─────────┴───────┴───────┘

Req/Bytes counts sampled once per second.

75 requests in 10.07s, 11.3 kB read
[==  ] Analysing data/Users/mdowns/.nvm/versions/node/v10.16.0/lib/node_modules/clinic/node_modules/@nearform/doctor/format/trace-event-decoder.js:49
          self.clockOffset = systemInfo.clockOffset
                                        ^

TypeError: Cannot read property 'clockOffset' of undefined
    at /Users/mdowns/.nvm/versions/node/v10.16.0/lib/node_modules/clinic/node_modules/@nearform/doctor/format/trace-event-decoder.js:49:41
    at Endpoint.finish (/Users/mdowns/.nvm/versions/node/v10.16.0/lib/node_modules/clinic/node_modules/endpoint/endpoint.js:36:5)
    at Object.onceWrapper (events.js:286:20)
    at Endpoint.emit (events.js:203:15)
    at finishMaybe (_stream_writable.js:646:14)
    at endWritable (_stream_writable.js:663:3)
    at Endpoint.Writable.end (_stream_writable.js:594:5)
    at onend (/Users/mdowns/.nvm/versions/node/v10.16.0/lib/node_modules/clinic/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:646:10)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

Clinic 5.0.0
node v10.16.0
npm 6.11.3
OS X 10.15.3

Followed the same steps as above.

**Comment by DylanC** [comment]
@mrdowns 

I tried this again with your exact version of Node installed through NVM. The example still worked for me just fine.

` clinic doctor --autocannon [ / ] -- node ./node-clinic-doctor-examples/slow-io`

Clinic.js version:
Clinic 5.0.0 and doctor 4.1.0
Node.js version:
Node 10.16 and npm 6.13.7
Browser name and version:
Chrome 80.0.3987.106 
Operating system and version:
OS X 10.14.6

**Comment by mrdowns** [comment]
Luckily the tests on node-clinic-doctor are failing for me locally with the same error, so I'm going to try to debug what's going on.

```
 FAIL  test/cmd-visualize.test.js
 ✖ Cannot read property 'clockOffset' of undefined

  format/trace-event-decoder.js
  47 |           // Save clock offset
  48 |           const systemInfo = data[0]
> 49 |           self.clockOffset = systemInfo.clockOffset
     | ----------------------------------------^
  50 |
  51 |           // Now that the clock offset is known, the data can be processed
  52 |           self.parser.write(chunk, encoding)

  test: cmd - test visualization - data exists
  stack: >
    format/trace-event-decoder.js:49:41

    Endpoint.finish (node_modules/endpoint/endpoint.js:36:5)

    onend (node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:646:10)
  type: TypeError
  tapCaught: uncaughtException
```

**Comment by goto-bus-stop** [comment]
Can you check the contents of the `.clinic/{pid}.clinic-doctor/{pid}.clinic-doctor-systeminfo` file?

**Comment by mrdowns** [comment]
That file(s) look like this:
```
{
  "clock": {
    "hrtime": [
      142643,
      210516535
    ],
    "unixtime": 1581955925744
  },
  "nodeVersions": {
    "http_parser": "2.8.0",
    "node": "10.16.0",
    "v8": "6.8.275.32-node.52",
    "uv": "1.28.0",
    "zlib": "1.2.11",
    "brotli": "1.0.7",
    "ares": "1.15.0",
    "modules": "64",
    "nghttp2": "1.34.0",
    "napi": "4",
    "openssl": "1.1.1b",
    "icu": "64.2",
    "unicode": "12.1",
    "cldr": "35.1",
    "tz": "2019a"
  },
  "toolVersion": "4.1.0"
}
```

When I was debugging the unit tests, it looks like inside trace-event-decoder.js, systemInfoReader is  piping an empty array to data, so data[0] is undefined on line 48.

This is especially strange since, if I go out to index.js and put the following code on like 159, right after systemInfoReader is initialized, it outputs the actual file:

```
    systemInfoReader.pipe(endpoint({ objectMode: true }, function (err, data) {
        let sysinfo = data[0];
        console.log('sysinfo', sysinfo);
    }));
```

I haven't got much past that in terms of looking into this - it doesn't make sense to me why systemInfoReader gives normal output after it's initialized, but an empty array after it gets passed into TraceEventDecoder.
