### ISSUE TITLE
clinic doctor crash - dataError

### ISSUE THREAD

**Issue by DaelDe** [nearform/node-clinic#257]
## Expected Behavior
Clinic doctor should not crash

## Current Behavior
```
y:\eadb\bin>clinic doctor --collect-only -- node run 
To stop data collection press: Ctrl + C
- Analysing dataError: No files matching the pattern found
    at notFound (C:\Users\dagr2587\AppData\Roaming\npm\node_modules\clinic\node_modules\@nearform\node-trace-log-join\index.js:66:15)
    at combine (C:\Users\dagr2587\AppData\Roaming\npm\node_modules\clinic\node_modules\@nearform\node-trace-log-join\index.js:25:34)
    at C:\Users\dagr2587\AppData\Roaming\npm\node_modules\clinic\node_modules\@nearform\node-trace-log-join\index.js:21:5
```
## Steps to Reproduce (for bugs)

1. execute clinic doctor

I am not able to share the sources of my project. It is a command line app developed with https://oclif.io/

## Environment

* Clinic.js version: v6.0.2
* Doctor: v5.0.2

* Node.js version: v12.14.1
* npm: 6.14.7

* Browser name and version:

* Operating system and version:  Windows 10 64-bit

**Comment by bradphelan** [comment]
The error message should display the pattern for better diagnosis. For reference the pattern being looked for is

```
node_trace.*.log
```

``C:\Users\brad\AppData\Roaming\npm\node_modules\clinic\node_modules\@nearform\node-trace-log-join\index.js`` 

I can confirm that no file matching that pattern was created in the directory or below from which I ran

```
npx clinic doctor -- node build/server.js
```
