### ISSUE TITLE
node instance does not start with clinic bubbleprof but starts with flame

### ISSUE THREAD

**Issue by tanmaypatil** [nearform/node-clinic#258]
## Expected Behavior
node process should start with clinic bubbleprof command however it works for clinic flame command  

## Current Behavior
node process crashes with error .
**command** 
```
clinic bubbleprof -- node src/start.js

    Error: npm.load() required
    at Object.get (/usr/local/lib/node_modules/npm/lib/npm.js:61:13)
    at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at process.emit (events.js:189:13)
    at process._fatalException (internal/bootstrap/node.js:496:27)

    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:653:13)
    at Object.<anonymous> (/Users/tanmay.patil/sales-demo/query-store/digital-quest/node_modules/@igtb-digital/digital-quest-commons/src/dataHandlers/depScope.js:9:31)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at loader (/Users/tanmay.patil/sales-demo/query-store/digital-quest/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/tanmay.patil/sales-demo/query-store/digital-quest/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/tanmay.patil/sales-demo/query-store/digital-quest/node_modules/@igtb-digital/digital-quest-commons/src/dataHandlers/index.js:2:31)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at loader (/Users/tanmay.patil/sales-demo/query-store/digital-quest/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/tanmay.patil/sales-demo/query-store/digital-quest/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:600:32)
process exited by signal SIGABRT
[    ] Analysing dataundefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Parser._flush (/usr/local/lib/node_modules/clinic/node_modules/@nearform/trace-events-parser/index.js:58:24)
    at Parser.prefinish (_stream_transform.js:141:10)
    at Parser.emit (events.js:189:13)
    at prefinish (_stream_writable.js:630:14)
    at finishMaybe (_stream_writable.js:638:5)
    at endWritable (_stream_writable.js:649:3)
    at Parser.Writable.end (_stream_writable.js:589:5)
    at TraceEventDecoder._flush (/usr/local/lib/node_modules/clinic/node_modules/@nearform/bubbleprof/format/trace-event-decoder.js:67:17)
    at TraceEventDecoder.prefinish (_stream_transform.js:141:10)
```

## Steps to Reproduce (for bugs)

1.  npm install -g clinic 
2. clinic bubbleprof -- node src/start.js

## Environment

* Clinic.js version: v6.0.2

* Node.js version: v10.15.3 , npm - v10.15.3

* Browser name and version: NA 

* Operating system and version: Mac OS 10.12.6

**Comment by mcollina** [comment]
Can you include a sample code to reproduce your problem?

**Comment by tanmaypatil** [comment]
Unfortunately Source code is huge in size ,will not be possible to share .

**Comment by mcollina** [comment]
I can't help if there is no script to reproduce.

**Comment by tanmaypatil** [comment]
Hi Matteo, 

In case it helps , this is the start.js 
```
// Added for regenerator runtime!!
require('babel-polyfill');
// Transpile on the fly
require('babel-register')({
  ignore: false,
  only: /\/(src|queryStore)/,
});

global.APP_ROOT = global.APP_ROOT || __dirname;

// // Additional config loading for priming
// const path = require('path');

// const loadPath = path.join(__dirname, '../.env');
// // // Local config loader
// require('dotenv').config({ silent: false, path: loadPath });

// Starting server
const { serverUtil } = require('./common');

serverUtil.getServer().startServer(__dirname);

**Comment by mcollina** [comment]
I need something I can use to reproduce the problem you are having :(
