### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by BridgeAR** [nearform/node-clinic#37]
Currently the RegExp is not safe and at least a better error message should be visible in this case.

The documentation seems to be outdated as well as the output file is actually `PID.clinic-flame`.

```
Clinic Flame - v2.1.0 (0x v4.1.3)
...
You can then transfer the data and visualize it locally:

  clinic flame --visualize-only PID.flamegraph
```

```
clinic flame --visualize-only 13083.flamegraph
```

```
/home/ruben/.nvm/versions/node/v10.8.0/lib/node_modules/clinic/bin.js:256
    const name = filename.match(/clinic-([^-]+)/)[1]
                                                 ^

TypeError: Cannot read property '1' of null
    at viz (node/v10.8.0/lib/node_modules/clinic/bin.js:256:50)
    at runTool (node/v10.8.0/lib/node_modules/clinic/bin.js:228:5)
    at Command.func (node/v10.8.0/lib/node_modules/clinic/bin.js:176:34)
    at Command.call (node/v10.8.0/lib/node_modules/clinic/node_modules/commist/index.js:100:8)
    at Object.parse (node/v10.8.0/lib/node_modules/clinic/node_modules/commist/index.js:58:19)
    at Object.<anonymous> (node/v10.8.0/lib/node_modules/clinic/bin.js:182:4)
```

**Comment by mcollina** [comment]
Fixed in #38
