### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by stsvilik** [nearform/node-clinic#40]
## Expected Behavior

Module installs and is available for running

## Current Behavior

Error is thrown during `npm install`

```bash
npm ERR! code E404
npm ERR! 404 Not Found: @nearform/doctor@^3.0.0
```

## Steps to Reproduce (for bugs)

1. In console run `npm install -g clinic`

## Environment

* Clinic version: latest

* Node version: v10.6.0 npm v6.2.0

* Browser name and version: Chrome 68.0.3440.84

* Operating system and version: 
OSX 10.13.6

**Comment by mcollina** [comment]
I cannot reproduce. Can you try with Node 10.8.0 and npm 6.3.0? Maybe it's a transient problem.

I've also released doctor v3.0.3, because some of the metadata was not showing up on npm.

Let me know if this is still happening for you.

**Comment by stsvilik** [comment]
I'm running into same exact issues with Node 10.8.0/NPM 6.3.0.
```
npm verb stack Error: 404 Not Found: @nearform/bubbleprof@^1.1.0
npm verb stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
npm verb stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm verb stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
npm verb stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
npm verb stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
npm verb stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
npm verb stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
npm verb stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
npm verb stack     at runCallback (timers.js:693:18)
npm verb stack     at tryOnImmediate (timers.js:664:5)
npm verb stack     at processImmediate (timers.js:646:5)
```

**Comment by BridgeAR** [comment]
@stsvilik this seems to be an issue with npm, not with bubbleprof. Please open an issue in the proper repository.
