### ISSUE TITLE
Clinic flame "TypeError: "file" argument must be a non-empty string" 

### ISSUE THREAD

**Issue by alxolr** [nearform/node-clinic#62]
When using `clinic flame -- node index.js`
clinic v1.2.1
node 8.11.3
ubuntu 18.04

I am getting the following error:

## Current Behavior
Analysing data
/usr/lib/node_modules/clinic/bin.js:261
        if (err) throw err
                 ^

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:383:11)
    at spawnSync (child_process.js:519:38)
    at ticksToTree (/usr/lib/node_modules/clinic/node_modules/0x/lib/ticks-to-tree.js:30:21)
    at render (/usr/lib/node_modules/clinic/node_modules/0x/lib/render.js:19:17)
    at generateFlamegraph (/usr/lib/node_modules/clinic/node_modules/0x/index.js:76:22)
    at visualize (/usr/lib/node_modules/clinic/node_modules/0x/index.js:119:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

## Steps to Reproduce (for bugs)

1. Start profiling `clinic flame -- node.index`
2. `autocannon -c 5 -t 5 http://localhost:8080`
3. pressing CTRL+C
4. Getting the Error

## Environment

* Clinic version: 

* Node version: 

* Browser name and version: 

* Operating system and version:

**Comment by BridgeAR** [comment]
I am able to reproduce it and I'll have a closer look.
