### ISSUE TITLE
how can i  solve this problem : process exited with exit code 9

### ISSUE THREAD

**Issue by ainitgit** [nearform/node-clinic#8]
My project has been launched, and it is running normally. 
It can be started by normal : node www.js, 
or it can be started by : pm2 www.js.

i use command: clinic doctor -- node www.js 
,then print these:

node: --trace-event-categories is not allowed in NODE_OPTIONS
/root/nvm/versions/node/v8.6.0/lib/node_modules/clinic/bin.js:209
      if (err) throw err
               ^

Error: process exited with exit code 9
    at ChildProcess.<anonymous> (/root/nvm/versions/node/v8.6.0/lib/node_modules/clinic/node_modules/@nearform/clinic-doctor/index.js:65:13)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

**Comment by mcollina** [comment]
You should use node 9.4.0+ - in some cases this would also work on Node 8.9.4 See https://github.com/nearform/node-clinic-doctor#supported-node-versions.

**Comment by ainitgit** [comment]
Thank you, mcollina
